In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import os

In [5]:
path_to_metadata = "/Volumes/ExSSD/UserData/GoogleDrive/01_files/001_Studium/001 Semester/06 FS25/09_BA/dataset/info/labels/"
metadata_files = os.listdir(path_to_metadata)

In [6]:
metadata = pd.DataFrame()

for file in metadata_files:
    metadata = pd.concat([metadata, pd.read_csv(path_to_metadata + file)], ignore_index=True)

In [14]:
metadata.groupby("label", dropna=False).count()

,session,SerialNumber,seq_nr,seq_id,Directory,DateTime_start,DateTime_end,duration_seconds,first_file,last_file,n_files,all_files,duplicate_label,label2
label,,,,,,,,,,,,,,
apodemus_sp,13669,13668,13669,13669,13669,13668,13668,13668,13669,13669,13669,13669,13626,13669
"apodemus_sp,crocidura_sp",16,16,16,16,16,16,16,16,16,16,16,16,16,16
"apodemus_sp,crocidura_sp,myodes_glareolus",1,1,1,1,1,1,1,1,1,1,1,1,1,1
"apodemus_sp,glis_glis",1,1,1,1,1,1,1,1,1,1,1,1,1,1
"apodemus_sp,microtus_sp",4,4,4,4,4,4,4,4,4,4,4,4,4,4
"apodemus_sp,myodes_glareolus",40,40,40,40,40,40,40,40,40,40,40,40,40,40
"apodemus_sp,myodes_glareolus,crocidura_sp",1,1,1,1,1,1,1,1,1,1,1,1,1,1
"apodemus_sp,myodes_glareolus,crocidura_sp,microtus_sp",1,1,1,1,1,1,1,1,1,1,1,1,1,1
"apodemus_sp,sorex_sp",2,2,2,2,2,2,2,2,2,2,2,2,2,2
chionomys_nivalis,59,59,59,59,59,59,59,59,59,59,59,59,0,59
crocidura_sp,1163,1163,1163,1163,1163,1163,1163,1163,1163,1163,1163,1163,1163,1163
"crocidura_sp,apodemus_sp",10,10,10,10,10,10,10,10,10,10,10,10,10,10
"crocidura_sp,microtus_sp",1,1,1,1,1,1,1,1,1,1,1,1,1,1
"crocidura_sp,myodes_glareolus",2,2,2,2,2,2,2,2,2,2,2,2,2,2
"crocidura_sp,sorex_sp",2,2,2,2,2,2,2,2,2,2,2,2,2,2
glis_glis,4,4,4,4,4,4,4,4,4,4,4,4,4,4
microtus_sp,659,659,659,659,659,659,659,659,659,659,659,659,282,659
"microtus_sp,apodemus_sp",1,1,1,1,1,1,1,1,1,1,1,1,1,1
mustela_erminea,1035,1035,1035,1035,1035,1035,1035,1035,1035,1035,1035,1035,13,1035
myodes_glareolus,4611,4602,4611,4611,4611,4602,4602,4602,4611,4611,4611,4611,4599,4611
"myodes_glareolus,apodemus_sp",62,62,62,62,62,62,62,62,62,62,62,62,62,62
"myodes_glareolus,crocidura_sp",5,5,5,5,5,5,5,5,5,5,5,5,5,5
"myodes_glareolus,microtus_sp",3,3,3,3,3,3,3,3,3,3,3,3,3,3
"myodes_glareolus,microtus_sp,sorex_sp",1,1,1,1,1,1,1,1,1,1,1,1,1,1
neomys_sp,8,8,8,8,8,8,8,8,8,8,8,8,8,8
sorex_sp,936,936,936,936,936,936,936,936,936,936,936,936,919,936
"sorex_sp,apodemus_sp",2,2,2,2,2,2,2,2,2,2,2,2,2,2
"sorex_sp,myodes_glareolus",1,1,1,1,1,1,1,1,1,1,1,1,1,1
NaN,933,933,933,933,933,933,933,933,933,933,933,933,930,0

In [11]:
metadata["label2"].unique()

array([nan, 'apodemus_sp', 'mustela_erminea', 'soricidae', 'cricetidae',
       'other', 'glis_glis'], dtype=object)

In [12]:
metadata[metadata["label2"].isna()]

,session,SerialNumber,seq_nr,seq_id,Directory,DateTime_start,DateTime_end,duration_seconds,first_file,last_file,n_files,all_files,label,duplicate_label,label2
0,1,H,1,1000000,sessions/session_01/H_2,2019-08-29T12:54:11Z,2019-08-29T12:54:12Z,1.0,RCNX0001.JPG,RCNX0003.JPG,3,"RCNX0001.JPG,RCNX0002.JPG,RCNX0003.JPG",NaN,0.0,NaN
7,1,H550HF07158832,1,1000007,sessions/session_01/H550HF07158832,2019-09-26T08:38:36Z,2019-09-26T08:38:39Z,3.0,IMG_0001.JPG,IMG_0003.JPG,3,"IMG_0001.JPG,IMG_0002.JPG,IMG_0003.JPG",NaN,0.0,NaN
10,1,H550HF07158839,1,1000010,sessions/session_01/H550HF07158839_1,2019-08-29T23:45:49Z,2019-08-29T23:45:50Z,1.0,IMG_0001.JPG,IMG_0003.JPG,3,"IMG_0001.JPG,IMG_0002.JPG,IMG_0003.JPG",NaN,0.0,NaN
12,1,H550HF07158839,3,1000012,sessions/session_01/H550HF07158839_1,2019-09-01T00:38:54Z,2019-09-01T00:38:56Z,2.0,IMG_0019.JPG,IMG_0021.JPG,3,"IMG_0019.JPG,IMG_0020.JPG,IMG_0021.JPG",NaN,0.0,NaN
13,1,H550HF07158839,4,1000013,sessions/session_01/H550HF07158839_1,2019-09-01T20:58:12Z,2019-09-01T20:58:13Z,1.0,IMG_0022.JPG,IMG_0024.JPG,3,"IMG_0022.JPG,IMG_0023.JPG,IMG_0024.JPG",NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21698,4,H550HF08161368,240,4018689,sessions/session_04/W7-WK06,2020-07-18T09:53:02Z,2020-07-18T09:53:02Z,0.0,IMG_4273.JPG,IMG_4275.JPG,3,"IMG_4273.JPG,IMG_4274.JPG,IMG_4275.JPG",NaN,0.0,NaN
21699,4,H550HF08161368,241,4018690,sessions/session_04/W7-WK06,2020-07-18T10:38:06Z,2020-07-18T10:38:10Z,4.0,IMG_4276.JPG,IMG_4278.JPG,3,"IMG_4276.JPG,IMG_4277.JPG,IMG_4278.JPG",NaN,0.0,NaN
21701,3,H550HF07158839,2,3000001,sessions/session_03/28,2020-04-05T11:27:29Z,2020-04-05T11:27:38Z,9.0,IMG_0070.JPG,IMG_0075.JPG,6,"IMG_0070.JPG,IMG_0071.JPG,IMG_0072.JPG,IMG_007...",NaN,NaN,NaN
21702,3,H550HF07158839,3,3000002,sessions/session_03/28,2020-04-07T12:06:38Z,2020-04-07T12:06:46Z,8.0,IMG_0076.JPG,IMG_0084.JPG,9,"IMG_0076.JPG,IMG_0077.JPG,IMG_0078.JPG,IMG_007...",NaN,NaN,NaN
21714,3,HLPWDL05004578,1,3000014,sessions/session_03/31,2020-04-06T12:31:59Z,2020-04-06T12:32:00Z,1.0,RCNX0001.JPG,RCNX0003.JPG,3,"RCNX0001.JPG,RCNX0002.JPG,RCNX0003.JPG",NaN,NaN,NaN